name: hlsd
description: HLS(.m3u8 files) downloader.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0
  path_provider: ^2.0.15
  # chewie: ^0.9.10
  provider: ^6.0.5
  pedantic: ^1.8.0
  typeweight: ^2.0.2
  google_fonts: ^5.1.0
  # video_player: ^2.7.0
  moor_flutter: ^4.1.0
  # path_provider: ^2.0.0
  flutter_hls_parser: ^2.0.1
  better_player: ^0.0.83
  flutter_background_service: ^4.0.0
  flutter_local_notifications: ^15.1.0+1
  workmanager: ^0.5.1
  # device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  moor_generator: ^4.3.0

flutter:
  uses-material-design: true

scripts: derry.yaml
